version: '3.5'
volumes:
  postgres:


services:
  app:
    container_name: product-microservice
    image: product-microservice
    build: ./
    command: docker run postgres
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_RABBITMQ_HOST=inconv-rabbit-mq
    depends_on:
      - rabbitmq
      - postgres
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: /postgres
    volumes:
      - postgres:/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  rabbitmq:
    container_name: inconv-rabbit-mq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped