version: '3.5'
volumes:
  postgres:

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: /postgres
    volumes:
      - postgres:/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped